# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .Net Buil

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    call-another-reusable:
      uses: VPund/XUnitRepo/.github/workflows/Called.yml@main
      #uses: actions/setup-dotnet@v3
      with:
      dotnet-version: ${{ vars.JOB_NAME }}
   # steps:
     # uses: actions/checkout@v3
     # name: Setup .NET
  
     
     #name: Restore dependencies
     #run: dotnet restore "./XUnitApp/XUnitApp/XUnitApp.csproj"
     #name: Build
     #run: dotnet build "./XUnitApp/XUnitApp/XUnitApp.csproj" --no-restore
     #name: Test
     #run: dotnet test "./XUnitApp/XUnitAppTest/XUnitAppTest.csproj" --no-build --verbosity normal
