# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .Net Buil

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:

   job1:
   call-workflow:
    uses: ./XUnitRepo/.github/workflows/Called.yml

   job2:
   
   build:

    runs-on: ubuntu-latest
    needs: job1 
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
  
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ vars.JOB_NAME }}
    - name: Restore dependencies
      run: dotnet restore "./XUnitApp/XUnitApp/XUnitApp.csproj"
    - name: Build
      run: dotnet build "./XUnitApp/XUnitApp/XUnitApp.csproj" --no-restore
    - name: Test
      run: dotnet test "./XUnitApp/XUnitAppTest/XUnitAppTest.csproj" --no-build --verbosity normal
