name: reusable workflow
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
